#!/home/k0ta/anaconda3/bin/python3
# SPDX-FileCopyrightText: 2025 kotaro sato <obake831@gmail.com>
import sys

ans = 0.0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)




