#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025 kotaro sato <obake831@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause

import sys


data = sys.stdin.read().strip()


if data == "":
    sys.exit(1)

allowed = "0123456789+-*/(). "

for c in data:
    if c not in allowed:
        print(f"Error: Invalid character '{c}'", file=sys.stderr)
        sys.exit(1)

try:
    result = eval(data)
    print(result)
    sys.exit(0)


except Exception:
    print("Error: Calculation failed", file=sys.stderr)
    sys.exit(1)


